### PR TITLE
updated README file

### PR DESCRIPTION
**Pull request by lvllaby**

### CODE REVIEW

**Comment by Felix14-v2** [comment]
Why should they change it?

**Comment by lvllaby** [comment]
on their site, they have a link to modrinth and not curseforge

**Comment by Enderteck** [comment]
You should still put both I think but I'm all for it (modrinth is better)

**Comment by Enderteck** [comment]
You should also remove Linux from this note as it's supported now. MacOS is complicated though so you should leave it there.

README.md:

> Known Issues
> Linux and macOS may not work.
> 

Here's why it's complicated with apple (tldr: they're assholes like ususal):

https://en.wikipedia.org/wiki/Vulkan#Apple

**Comment by lvllaby** [comment]
added modrinth button and change linux note

**Comment by Zorklis** [comment]
"Linux is now supported" should be in the notes and not in Known Issues then.
Might as well add windows and change it to: "Windows and Linux are the supported platforms" just to clear the air

**Comment by xCollateral** [comment]
Duplicate of #383

**Pull request closed without merging**
