### PR TITLE
Little Update to README.md

### PR DESCRIPTION
**Pull request by SpidFightFR**
Adding more information in the "known issues" tab.
Removed "Linux may not work", as it do work.
Added a link to the archwiki explaining how to get vulkan to work on linux (it's pretty well explained).

Didn't change the "macOS may not work" as i don't own a mac, i can't really tell if that's still the case.

### CODE REVIEW

**Comment by thr3343** [comment]
I'm likely wrong about this as I don't run Linux or have an AMD GPU, but the Linux disclaimer may be referring to the RADV AMD Drivers, which apparently seem to have the most issues with this mod for some reason (Including Swapchain-related bugs apparently).

**Comment by Vixea** [comment]
https://i.imgur.com/0wFDoKm.jpg
@thr3343 tested on RADV works fine now! :D

**Comment by ghost** [comment]
AMDGPU users still having some issues with it, like everytime the mod update something will break and cause driver crashes. We're not sure about it's Mesa thing, but Collateral tried his best to fix it.

**Comment by Vixea** [comment]
Have they tried forcing vsync?

**Pull request closed without merging**
