### PR TITLE
[Vulkan 1.2] Implement Bindless rendering

### PR DESCRIPTION
**Pull request by thr3343**
Similar to the prior PR https://github.com/xCollateral/VulkanMod/pull/422, but with significant stability + visual fixes and code quality improvements

Enhances VulkanMod's internal engine _(i.e. the renderer)_ by utilizing Vulkan 1.2 features to implement bindless rendering

* CPU overhead improvements, 
* Chunk and entity rendering performance is increased
* New features such as Bindless textures and Bindless uniforms
* Adds support for additional features, such as Anisotropic Filtering, MSAA, and UberShaders

#### Issues fixed from prior PR

* Is now compatible with MoltenVK + intel iGPUs 
* Many shader and visual glitches fixed
* PushConstants are now updated at the correct intervals _(Fixes lighting glitches)_

#### Current Issues

* Reduced CPU improvements on MoltenVK + Intel iGPUs
  * Some drivers have very low texture slot limits; is a non-fixable hardware limitation
  * Worked around by implementing a `semi-bindless` mode, which restores MoltenVk compatibility but has increased CPU usage relative to `Fully Bindless` mode
  * Drivers supporting texture limits >16384 don't have this issue, and can use the default `Fully Bindless` mode
 * No longer supports Vulkan 1.1
   * Due to using Vulkan 1.2 features, which are not available in core 1.1

#### Minor visual bugs, _(from the previous PR)_
* New textures rendered for the first time are skipped for 1 frame; causes temporary texture flicker: 
  * Happens only once during runtime, subsequent usages of that texture do not incur flickering
* Graphics menu navigation arrows use the incorrect fill color 
  * Caused by menu and sky background both using the same shader
 * Sky Color transitions between biomes are delayed by one frame

### CODE REVIEW

**Comment by ghost** [comment]
Crash on load on Apple M1 (MoltenVK).
[crash-2024-07-18_14.55.38-client.txt](https://github.com/user-attachments/files/16280490/crash-2024-07-18_14.55.38-client.txt)

**Comment by thr3343** [comment]
> Crash on load on Apple M1 (MoltenVK). [crash-2024-07-18_14.55.38-client.txt](https://github.com/user-attachments/files/16280490/crash-2024-07-18_14.55.38-client.txt)

@seji1 The issue should be fixed now.

I made a typo and incorrectly set the descriptor pool sizes too small, which caused `VK_ERROR_OUT_OF_POOL_MEMORY` on non-Nvidia GPUs

_(Could reproduce this on an intel iGPU as well)_

**Comment by ghost** [comment]
> > Crash on load on Apple M1 (MoltenVK). [crash-2024-07-18_14.55.38-client.txt](https://github.com/user-attachments/files/16280490/crash-2024-07-18_14.55.38-client.txt)
> 
> @seji1 The issue should be fixed now.
> 
> I made a typo and incorrectly set the descriptor pool sizes too small, which caused `VK_ERROR_OUT_OF_POOL_MEMORY` on non-Nvidia GPUs
> 
> _(Could reproduce this on an intel iGPU as well)_

Yep, seems to be fixed, but now i'm getting another error on startup😅
[crash-2024-07-18_20.16.05-client.txt](https://github.com/user-attachments/files/16284565/crash-2024-07-18_20.16.05-client.txt)

**Comment by thr3343** [comment]
> > > Crash on load on Apple M1 (MoltenVK). [crash-2024-07-18_14.55.38-client.txt](https://github.com/user-attachments/files/16280490/crash-2024-07-18_14.55.38-client.txt)
> > 
> > 
> > @seji1 The issue should be fixed now.
> > I made a typo and incorrectly set the descriptor pool sizes too small, which caused `VK_ERROR_OUT_OF_POOL_MEMORY` on non-Nvidia GPUs
> > _(Could reproduce this on an intel iGPU as well)_
> 
> Yep, seems to be fixed, but now i'm getting another error on startup😅 [crash-2024-07-18_20.16.05-client.txt](https://github.com/user-attachments/files/16284565/crash-2024-07-18_20.16.05-client.txt)

That's an LWJGL related crash, and has nothing to do with VulkanMod or this PR
This normally happens when you use 3.3.3 instead of 3.3.2, however the log says your using 3.3.2, which should be the correct version.

I would try updating your LWJGL version first, though it might take a few attempts to find a working LWJGL version

_(Sorry about this, VulkanMod's libraries are not always the most stable sometimes)_

**Comment by ghost** [comment]
Tried changing versions of lwjgl and joml in build, but doesn't seem to do anything. 

Maybe it's some unfixed bug in mac builds or problem with my machine, we need someone else with mac to test this. Not really sure. Though i don't have any problems with main branch

**Comment by ghost** [comment]
Hello, i'm here with another crash log. I managed to boot up the game on latest commit, but when joining the world  it fails to create graphics pipeline

[crash-2024-07-19_12.33.50-client.txt](https://github.com/user-attachments/files/16303168/crash-2024-07-19_12.33.50-client.txt)

Also upon clicking any button for the first time (changing menu) i can see some artifacts, almost the same as when loading the game. Probably MoltenVK issue

https://github.com/user-attachments/assets/997ddef8-6ee9-4614-9c1e-694aa52c61f9

**Comment by thr3343** [comment]
> Hello, i'm here with another crash log. I managed to boot up the game on latest commit, but when joining the world it fails to create graphics pipeline
> 
> [crash-2024-07-19_12.33.50-client.txt](https://github.com/user-attachments/files/16303168/crash-2024-07-19_12.33.50-client.txt)
> 
> Also upon clicking any button for the first time (changing menu) i can see some artifacts, almost the same as when loading the game. Probably MoltenVK issue
> 
>  artifacts.mov

Thanks alot for testing this

Currently suspect that MoltenVK may have problems with Vk1.2, as all the Vk1.2 features used in this PR work fine and are glitch free on Linux + Windows with multiple GPUs

The "Failed to create graphics pipeline" crash is a separate issue, and is likely caused by Spec constants, which are a new feature this PR uses to optimize chunk rendering performance

Spec constants are supported on all Vulkan devices though, so there is no reason why MoltenVk should crash when using them

Will do some testing on my end to try to figure out the cause _(likely test builds in the discord)_


_(tl;dr: MoltenVK's Vk1.2 support might be bugged, need to do some troubleshooting + testing to confirm this though)_

**Comment by Vixea** [comment]
I'm interested to see if this will help increase my fps on riscv. As the cpus are still rather weak though not for long with new boards coming out.

**Comment by Vixea** [comment]
Umm either newer commits in master fixed some issues, or this pr completely breaks things, textures are just gone

**Comment by Vixea** [comment]
Btw heres the logs vkangry.txt

Edit i just realized im using outdated code let me try the latest ver 3 and ill edit with a new log

**Comment by Vixea** [comment]
Feature not available(descriptor indexing) rip whenever this gets merged then, could you pretty please make a version with the rest of the optimizations? Ie only inline uniform blocks

**Comment by thr3343** [comment]
This PR had serveral design issues

Namely that it forced Bindless mode on all Devices, even if it was unsupported on the hardware, which is likely the cause of the glitches on MoltenVK

So will replace with a new branch/PR in a moment or so

The replacement PR won't need Descriptor indexing in Non-Bindless mode, but will still require the Vulkan 1.2 feature `runtimeDescriptorArray` to avoid writing separate Non-Bindless and Bindless shaders

**Comment by Vixea** [comment]
Btw i would not recommend rebasing to the newest commit as there definitely was a barrier that shouldn't have been removed and eventually the game will "freeze" unless you also wanna fix that

**Comment by thr3343** [comment]
> Btw i would not recommend rebasing to the newest commit as there definitely was a barrier that shouldn't have been removed and eventually the game will "freeze" unless you also wanna fix that

Will let Collateral know that upstream has broken barriers + Sync hazards, thanks for the info

I will avoid touching barriers though as they are unrelated to Bindless rendering, and want to avoid the PR getting too large and causing potential merge conflicts

**Comment by thr3343** [comment]
Replaced with https://github.com/xCollateral/VulkanMod/pull/467

**Pull request closed without merging**
