### PR TITLE
Add language support for the german language

### PR DESCRIPTION
**Pull request by Strokkur424**
Implemented language support for the german language in VulkanMod

### CODE REVIEW

**Comment by NXTler** [comment]
That's a very bad translation.
"[...] Es verändert den Aspekt von einigen entfernten Blöcken" Aspekt is clearly the wrong word here, as it means something like Angle of view, direction of view, viewpoint, point of view.
And the General phrasing is too much English like, with a bad flow and oversimplifications.

**Comment by NXTler** [comment]
There is also no point in doing translations without having #421 merged.

**Comment by Strokkur424** [comment]
Very well. Will update the PR once #421 has been merged

**Comment by Strokkur424** [comment]
> That's a very bad translation. "[...] Es verändert den Aspekt von einigen entfernten Blöcken" Aspekt is clearly the wrong word here, as it means something like Angle of view, direction of view, viewpoint, point of view. And the General phrasing is too much English like, with a bad flow and oversimplifications.

Strangely enough I agree. Eventhough I am german, the issue is, that I have no clue what the original language even ment by aspect. Once #421 has been merged I will redo some of them and figure out better translations if that is alright

**Comment by NXTler** [comment]
If you want, we can collaborate once it has been merged. Just ping me here if you need another opinion or idea. I think aspect is used in the sense of "Erscheinung" in this case.

**Pull request closed without merging**
