### PR TITLE
WIP update for LWJGL 3.3.0

### PR DESCRIPTION
**Pull request by unit-a-user**
Indigo renderer issue: https://github.com/orgs/FabricMC/discussions/2231 (discussion)
It's works when "you have to set always-tesselate-blocks=false in config/fabric/indigo-renderer.properties"

What I changed: 
- ~~replaced `com.example` to `net.vulkanmod`~~
- ~~update `yarn_mappings=1.18.2+build.3`~~
- ~~update `fabric_version=0.51.1+1.18.2`~~
- ~~update `loader_version=0.14.5`~~
- ~~increased memory `org.gradle.jvmargs=-Xmx4G`~~
- tried `project.ext.lwjglVersion = "3.3.0"`
- fix `allocatorCreateInfo.instance(instance);` in `Vulkan.java`
- ~~avoid `.vs` or `.vc` folder from upload~~
- rise back byte color instead of float, back compatibility with indigo tessellation

### CODE REVIEW

**Comment by unit-a-user** [comment]
It's works when "you have to set `always-tesselate-blocks=false` in `config/fabric/indigo-renderer.properties`"

**Comment by arlomcwalter** [comment]
why are you allocating 8gb to a development environment? seems very excessive

**Comment by unit-a-user** [comment]
First of all, it is not a fact that 8Gb, because the flag indicates the maximum capacity. Secondly, just in case, in case an overflow or slowdown occurs.

**Comment by polarbub** [comment]
How do you get around Minecraft trying to load its own lwjgl?

**Comment by polarbub** [comment]
For blaze4d I use multimc to disable the default lwjgl 3.2.3 and use 3.3.1

**Comment by arlomcwalter** [comment]
> First of all, it is not a fact that 8Gb, because the flag indicates the maximum capacity. Secondly, just in case, in case an overflow or slowdown occurs. Do you propose to leave it like that, or to assign only 4Gb? Thirdly, systems now rarely have less than 8 or 16 Gb of RAM, with rare exceptions.

i understand, lol. it's just very excessive, i've never even had an issue with capping it at 2gb. sure it wont necessarily use 8gb but thats not a reason to max it at 8gb, what if someone only has an 8gb system? (not very uncommon)

**Comment by polarbub** [comment]
Does it work in the vanilla launcher?

**Comment by unit-a-user** [comment]
Mod probably yes, IDK.
But update LWJGL for vanilla probably not possible due recursive hashing.

**Comment by polarbub** [comment]
Are you saying you used the customize button in multimc for lwjgl?

**Comment by unit-a-user** [comment]
> Are you saying you used the customize button in multimc for lwjgl?
Yes, but I'm also used JavaScript script, because I'm tired writing every checksum by hand. 
Also, final answer about official launcher: **YES!**

**Comment by unit-a-user** [comment]
Also, `R8G8B8A8_UNORM` is works. And `always-tesselate-blocks=auto` is works!

**Review by xCollateral — CHANGES_REQUESTED** [review]
Would you remove non reviewed files from pr?
Besides that good work.

**Comment by unit-a-user** [comment]
> Would you remove non reviewed files from pr? Besides that good work.

I apologize for the question of what files are we talking about, specify?

**Comment by xCollateral** [comment]
Gradle settings files, and `Vulkan.java`. `.gitignore` is fine.
Let every user chose these config.

**Comment by unit-a-user** [comment]
Rise back `gradle.properties` and `.gitignore`.

**Comment by xCollateral** [comment]
I'll merge this, but i think i'll just update to lwjgl 3.31 later.

**Review by xCollateral — APPROVED** [review]

**Pull request merged**
